# 환경 설정

In [15]:
import numpy as np

# Process Tree Generation

In [3]:
import pm4py
from pm4py.algo.simulation.tree_generator import algorithm as pt_generator

In [ ]:
parameters_naive = {}
parameters_naive['min'] = 7
parameters_naive['mode'] = 7
parameters_naive['max'] = 7
parameters_naive['sequence'] = 1
parameters_naive['choice'] = 0
parameters_naive['parallel'] = 0
parameters_naive['loop'] = 0
parameters_naive['or'] = 0
parameters_naive['silent'] = 0
parameters_naive['duplicate'] = 0
parameters_naive['lt_depencency'] = 0
parameters_naive['infrequent'] = 0
parameters_naive['unfold'] = 0
parameters_naive['max_repeat'] = 0

parameters_simple = {}
parameters_simple['min'] = 5
parameters_simple['mode'] = 7
parameters_simple['max'] = 9
parameters_simple['sequence'] = 0.7
parameters_simple['choice'] = 0.3
parameters_simple['parallel'] = 0
parameters_simple['loop'] = 0
parameters_simple['or'] = 0
parameters_simple['silent'] = 0
parameters_simple['duplicate'] = 0
parameters_simple['lt_depencency'] = 0
parameters_simple['infrequent'] = 0
parameters_simple['unfold'] = 0
parameters_simple['max_repeat'] = 0

parameters_concise = {}
parameters_concise['min'] = 5
parameters_concise['mode'] = 7
parameters_concise['max'] = 9
parameters_concise['sequence'] = 0.25
parameters_concise['choice'] = 0.25
parameters_concise['parallel'] = 0.25
parameters_concise['loop'] = 0.25
parameters_concise['or'] = 0
parameters_concise['silent'] = 0
parameters_concise['duplicate'] = 0
parameters_concise['lt_depencency'] = 0
parameters_concise['infrequent'] = 0
parameters_concise['unfold'] = 0
parameters_concise['max_repeat'] = 0

parameters_straightforward = {}
parameters_straightforward['min'] = 20
parameters_straightforward['mode'] = 20
parameters_straightforward['max'] = 20
parameters_straightforward['sequence'] = 1
parameters_straightforward['choice'] = 0
parameters_straightforward['parallel'] = 0
parameters_straightforward['loop'] = 0
parameters_straightforward['or'] = 0
parameters_straightforward['silent'] = 0
parameters_straightforward['duplicate'] = 0
parameters_straightforward['lt_depencency'] = 0
parameters_straightforward['infrequent'] = 0
parameters_straightforward['unfold'] = 0
parameters_straightforward['max_repeat'] = 0

parameters_complex = {}
parameters_complex['min'] = 15
parameters_complex['mode'] = 20
parameters_complex['max'] = 25
parameters_complex['sequence'] = 0.7
parameters_complex['choice'] = 0.3
parameters_complex['parallel'] = 0
parameters_complex['loop'] = 0
parameters_complex['or'] = 0
parameters_complex['silent'] = 0
parameters_complex['duplicate'] = 0
parameters_complex['lt_depencency'] = 0
parameters_complex['infrequent'] = 0
parameters_complex['unfold'] = 0
parameters_complex['max_repeat'] = 0

parameters_spaghetti = {}
parameters_spaghetti['min'] = 15
parameters_spaghetti['mode'] = 20
parameters_spaghetti['max'] = 25
parameters_spaghetti['sequence'] = 0.25
parameters_spaghetti['choice'] = 0.25
parameters_spaghetti['parallel'] = 0.25
parameters_spaghetti['loop'] = 0.25
parameters_spaghetti['or'] = 0
parameters_spaghetti['silent'] = 0
parameters_spaghetti['duplicate'] = 0
parameters_spaghetti['lt_depencency'] = 0
parameters_spaghetti['infrequent'] = 0
parameters_spaghetti['unfold'] = 0
parameters_spaghetti['max_repeat'] = 0

In [ ]:
processtree_naive = []
processtree_simple = []
processtree_concise = []
processtree_straightforward = []
processtree_complex = []
processtree_spaghetti = []

for i in range(100):
      process_tree = pt_generator.apply(parameters=parameters_naive)
      processtree_naive.append(process_tree)
for i in range(100):
      process_tree = pt_generator.apply(parameters=parameters_simple)
      processtree_simple.append(process_tree)
for i in range(100):
      process_tree = pt_generator.apply(parameters=parameters_concise)
      processtree_concise.append(process_tree)
for i in range(100):
      process_tree = pt_generator.apply(parameters=parameters_straightforward)
      processtree_straightforward.append(process_tree)
for i in range(100):
      process_tree = pt_generator.apply(parameters=parameters_complex)
      processtree_complex.append(process_tree)
for i in range(100):
      process_tree = pt_generator.apply(parameters=parameters_spaghetti)
      processtree_spaghetti.append(process_tree)


NameError: name 'parameters_naive' is not defined

In [1]:
import pickle

# 파일에 저장
def save_process_trees(process_trees, filename):
    with open(filename, 'wb') as file:
        pickle.dump(process_trees, file)

# 파일에서 불러오기
def load_process_trees(filename):
    with open(filename, 'rb') as file:
        process_trees = pickle.load(file)
    return process_trees

In [ ]:
# 파일에 저장
save_process_trees(processtree_naive, 'processtree_naive.pkl')
save_process_trees(processtree_simple, 'processtree_simple.pkl')
save_process_trees(processtree_concise, 'processtree_concise.pkl')
save_process_trees(processtree_straightforward, 'processtree_straightforward.pkl')
save_process_trees(processtree_complex, 'processtree_complex.pkl')
save_process_trees(processtree_spaghetti, 'processtree_spaghetti.pkl')

In [2]:
# 파일에서 불러오기
processtree_naive = load_process_trees('processtree_naive.pkl')
processtree_simple = load_process_trees('processtree_simple.pkl')
processtree_concise = load_process_trees('processtree_concise.pkl')
processtree_straightforward = load_process_trees('processtree_straightforward.pkl')
processtree_complex = load_process_trees('processtree_complex.pkl')
processtree_spaghetti = load_process_trees('processtree_spaghetti.pkl')

In [8]:
processtree_naive[0]

'→ ( a → ( → ( d → ( e → ( b f ) ) ) → ( c g ) ) )'

In [4]:
all_process_trees = []

# 각 그룹에 속한 트리들을 모두 하나의 리스트로 통합
all_process_trees.extend(processtree_naive)
all_process_trees.extend(processtree_simple)
all_process_trees.extend(processtree_concise)
all_process_trees.extend(processtree_straightforward)
all_process_trees.extend(processtree_complex)
all_process_trees.extend(processtree_spaghetti)

# Tokenizing

In [5]:
import re

def tokenize_tree(tree):
    # 특수 문자를 이스케이프하여 정규 표현식 적용 + 괄호는 넣기
    special_characters = r"[\*\+\./:;<=\?\[\]\^_`{|}~\(\)]"
    tokenized_tree = re.findall(r"\b\w+\b|" + special_characters + r"|\u2192", str(tree).replace("->", "\u2192"))
    return tokenized_tree

# Tokenize each group
tokenized_processtree_naive = [tokenize_tree(tree) for tree in processtree_naive]
tokenized_processtree_simple = [tokenize_tree(tree) for tree in processtree_simple]
tokenized_processtree_concise = [tokenize_tree(tree) for tree in processtree_concise]
tokenized_processtree_straightforward = [tokenize_tree(tree) for tree in processtree_straightforward]
tokenized_processtree_complex = [tokenize_tree(tree) for tree in processtree_complex]
tokenized_processtree_spaghetti = [tokenize_tree(tree) for tree in processtree_spaghetti]

In [6]:
all_tokenized_processtrees = []

# 토큰화된 트리들을 각 그룹에서 가져와서 통합
all_tokenized_processtrees.extend(tokenized_processtree_naive)
all_tokenized_processtrees.extend(tokenized_processtree_simple)
all_tokenized_processtrees.extend(tokenized_processtree_concise)
all_tokenized_processtrees.extend(tokenized_processtree_straightforward)
all_tokenized_processtrees.extend(tokenized_processtree_complex)
all_tokenized_processtrees.extend(tokenized_processtree_spaghetti)

In [7]:
# 전체 프로세스 트리에서 ->를 →로 대체
all_process_trees = [" ".join(tree) for tree in all_tokenized_processtrees]

In [8]:
# 전체 프로세스 트리를 100개씩 끊어 6개의 그룹에 나누기
chunk_size = 100
groups = [all_process_trees[i:i+chunk_size] for i in range(0, len(all_process_trees), chunk_size)]

# 6개의 그룹에 대해 각각 변수에 저장
processtree_naive = groups[0]
processtree_simple = groups[1]
processtree_concise = groups[2]
processtree_straightforward = groups[3]
processtree_complex = groups[4]
processtree_spaghetti = groups[5]

In [9]:
# 공통 어휘 구성
global_vocab = set()
for tokenized_processes in all_tokenized_processtrees:
      global_vocab.update(tokenized_processes)
global_vocab = sorted(global_vocab)

print("vocab 길이 : ", len(global_vocab))
print("\n사용된 vocab : ", global_vocab)

vocab 길이 :  31

사용된 vocab :  ['(', ')', '*', '+', 'X', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', '→']


# Bag-of-Words

In [ ]:
def bag_of_words(tokenized_processes, global_vocab):
    vocab_list = sorted(list(global_vocab))
    bows = []

    for tokenized_process in tokenized_processes:
        process_vocab = {word: index for index, word in enumerate(vocab_list)}
        process_bow = np.zeros(len(vocab_list), dtype=int)

        for word in tokenized_process:
            word_index = process_vocab.get(word)
            process_bow[word_index] += 1

        bows.append(process_bow)

    return bows

In [ ]:
# 각 그룹에 대해 벡터화된 표현 생성
bows_naive = bag_of_words(tokenized_processtree_naive, global_vocab)
bows_simple = bag_of_words(tokenized_processtree_simple, global_vocab)
bows_concise = bag_of_words(tokenized_processtree_concise, global_vocab)
bows_straightforward = bag_of_words(tokenized_processtree_straightforward, global_vocab)
bows_complex = bag_of_words(tokenized_processtree_complex, global_vocab)
bows_spaghetti = bag_of_words(tokenized_processtree_spaghetti, global_vocab)

# TF-IDF

In [ ]:
processtree_texts = [' '.join(tree) for tree in all_tokenized_processtrees]

# 결과 출력
print(processtree_texts)
print("길이 :",len(processtree_texts))

['→ ( a → ( → ( d → ( e → ( b f ) ) ) → ( c g ) ) )', '→ ( → ( c → ( b → ( f e ) ) ) → ( d → ( g a ) ) )', '→ ( → ( c → ( → ( e d ) → ( b g ) ) ) → ( f a ) )', '→ ( → ( → ( d → ( g a ) ) → ( c e ) ) → ( f b ) )', '→ ( → ( a → ( → ( f c ) → ( e g ) ) ) → ( b d ) )', '→ ( → ( c → ( f → ( g a ) ) ) → ( b → ( d e ) ) )', '→ ( → ( c b ) → ( a → ( e → ( d → ( g f ) ) ) ) )', '→ ( → ( a → ( f c ) ) → ( b → ( d → ( e g ) ) ) )', '→ ( → ( → ( d c ) → ( b → ( e f ) ) ) → ( a g ) )', '→ ( → ( → ( c d ) → ( g b ) ) → ( a → ( e f ) ) )', '→ ( → ( → ( a d ) → ( c f ) ) → ( e → ( b g ) ) )', '→ ( → ( b → ( f → ( c g ) ) ) → ( d → ( e a ) ) )', '→ ( b → ( c → ( → ( e a ) → ( d → ( g f ) ) ) ) )', '→ ( → ( c → ( → ( b e ) → ( d f ) ) ) → ( g a ) )', '→ ( → ( a → ( e → ( c → ( g f ) ) ) ) → ( b d ) )', '→ ( → ( → ( d c ) → ( a → ( e f ) ) ) → ( g b ) )', '→ ( b → ( → ( a → ( d → ( e f ) ) ) → ( g c ) ) )', '→ ( → ( → ( b → ( d f ) ) → ( c e ) ) → ( a g ) )', '→ ( → ( → ( c → ( d g ) ) → ( f b ) ) → ( e 

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
import re

# TF-IDF 모델 초기화
tfidf_vectorizer = TfidfVectorizer(token_pattern=r"(?u)\b\w+\b|[\(\)\'\*\+,/:;<=?\[\]^_`{|}~]|\u2192", lowercase=False)

# TF-IDF 변환
tfidf_matrix = tfidf_vectorizer.fit_transform(processtree_texts)

# 어휘 사전 가져오기
feature_names = tfidf_vectorizer.get_feature_names_out()

# 각 프로세스 트리에 대한 TF-IDF 벡터를 리스트로 추출
sentence_embeddings_tfidf = tfidf_matrix.toarray()

# TF-IDF 벡터를 6개로 나누어 저장
num_embeddings = len(sentence_embeddings_tfidf)
chunk_size = num_embeddings // 6

# 6개로 나눈 TF-IDF 벡터를 변수에 저장
sentence_embeddings_tfidf_naive = sentence_embeddings_tfidf[:chunk_size]
sentence_embeddings_tfidf_simple = sentence_embeddings_tfidf[chunk_size:2 * chunk_size]
sentence_embeddings_tfidf_concise = sentence_embeddings_tfidf[2 * chunk_size:3 * chunk_size]
sentence_embeddings_tfidf_straightforward = sentence_embeddings_tfidf[3 * chunk_size:4 * chunk_size]
sentence_embeddings_tfidf_complex = sentence_embeddings_tfidf[4 * chunk_size:5 * chunk_size]
sentence_embeddings_tfidf_spaghetti = sentence_embeddings_tfidf[5 * chunk_size:]


# Word Embeddings

## 모델 정의

In [ ]:
from gensim.models import Word2Vec

# Assuming 'tokenized_processtree' is a list of tokenized sentences
model_w2v = Word2Vec(sentences=all_tokenized_processtrees, vector_size=64, window=15, workers=4, sg=0, epochs=50)


In [ ]:
model_result = model_w2v.wv.most_similar("(")
print(model_result)

[(')', 0.9088013172149658), ('v', 0.6688251495361328), ('w', 0.5909003019332886), ('t', 0.5669628381729126), ('x', 0.5611428618431091), ('h', 0.49754780530929565), ('→', 0.4807727336883545), ('u', 0.47907891869544983), ('X', 0.47657790780067444), ('j', 0.45971184968948364)]


In [ ]:
from glove import Corpus, Glove

corpus = Corpus()

corpus.fit(all_tokenized_processtrees, window=15)
model_glove = Glove(no_components=64, learning_rate=0.1)

model_glove.fit(corpus.matrix, epochs=50, no_threads=4, verbose=False)
model_glove.add_dictionary(corpus.dictionary)

In [ ]:
print(model_glove.most_similar("("))

[('X', 0.9251966734131248), ('i', 0.9242474282677611), ('k', 0.8974082352122548), ('v', 0.8836331428390904)]


In [ ]:
# word dict 생성
word_dict = {}
for word in  model_glove.dictionary.keys():
    word_dict[word] = model_glove.word_vectors[model_glove.dictionary[word]]
print('사용된 토큰 길이 : ', len(word_dict))

사용된 토큰 길이 :  31


In [ ]:
from gensim.models import FastText

model_fasttext = FastText(sentences=all_tokenized_processtrees, vector_size=64, window=15, workers=4, sg=0, epochs=50)

In [ ]:
model_fasttext.wv.most_similar("(")

[(')', 0.9216074347496033),
 ('v', 0.7990978956222534),
 ('w', 0.7805248498916626),
 ('x', 0.692717969417572),
 ('X', 0.6361245512962341),
 ('t', 0.6224843263626099),
 ('h', 0.5981870293617249),
 ('s', 0.512075662612915),
 ('+', 0.48252761363983154),
 ('p', 0.4713887572288513)]

In [ ]:
def get_sentence_embeddings(tokenized_sentences, model):
    embeddings = []
    for sentence_tokens in tokenized_sentences:
        # Assuming you have a function named `sentence_embedding` for obtaining embeddings
        embedding = sentence_embedding(sentence_tokens, model)
        embeddings.append(embedding)
    return embeddings


## word2vec

In [ ]:
def sentence_embedding(sentence_tokens, model):
    # Initialize an empty array to store word vectors
    word_vectors = []

    # Iterate through the tokens in the sentence
    for token in sentence_tokens:
        if token in model.wv:
            # Keep the original 64-dimensional vector for each word
            word_vector = model.wv[token]
            word_vectors.append(word_vector)

    sentence_embedding = np.mean(word_vectors, axis=0, keepdims=False)
    return sentence_embedding

In [ ]:
# Create a list to store sentence embeddings for each group
sentence_embeddings_w2v_naive = []
sentence_embeddings_w2v_simple = []
sentence_embeddings_w2v_concise = []
sentence_embeddings_w2v_straightforward = []
sentence_embeddings_w2v_complex = []
sentence_embeddings_w2v_spaghetti = []

# Apply the sentence embeddings to each group
sentence_embeddings_w2v_naive = get_sentence_embeddings(tokenized_processtree_naive, model_w2v)
sentence_embeddings_w2v_simple = get_sentence_embeddings(tokenized_processtree_simple, model_w2v)
sentence_embeddings_w2v_concise = get_sentence_embeddings(tokenized_processtree_concise, model_w2v)
sentence_embeddings_w2v_straightforward = get_sentence_embeddings(tokenized_processtree_straightforward, model_w2v)
sentence_embeddings_w2v_complex = get_sentence_embeddings(tokenized_processtree_complex, model_w2v)
sentence_embeddings_w2v_spaghetti = get_sentence_embeddings(tokenized_processtree_spaghetti, model_w2v)

In [ ]:
np.array(sentence_embeddings_w2v_spaghetti).shape

(100, 64)

## glove

In [ ]:
def sentence_embedding(tokens, model, embedding_dim=64):
    size = len(tokens)
    matrix = np.zeros((size, embedding_dim))
    word_table = word_dict
    for i, token in enumerate(tokens):
        vector = np.array([
            word_table[t] for t in token
            if t in word_table
        ])

        if vector.size != 0:
            final_vector = np.mean(vector, axis=0)
            matrix[i] = final_vector

    sentence_embedding = np.mean(matrix, axis=0)

    return sentence_embedding

In [ ]:
# Create lists to store sentence embeddings for each group
sentence_embeddings_glove_naive = []
sentence_embeddings_glove_simple = []
sentence_embeddings_glove_concise = []
sentence_embeddings_glove_straightforward = []
sentence_embeddings_glove_complex = []
sentence_embeddings_glove_spaghetti = []

# Apply the sentence embeddings to each group
sentence_embeddings_glove_naive = get_sentence_embeddings(tokenized_processtree_naive, model_glove)
sentence_embeddings_glove_simple = get_sentence_embeddings(tokenized_processtree_simple, model_glove)
sentence_embeddings_glove_concise = get_sentence_embeddings(tokenized_processtree_concise, model_glove)
sentence_embeddings_glove_straightforward = get_sentence_embeddings(tokenized_processtree_straightforward, model_glove)
sentence_embeddings_glove_complex = get_sentence_embeddings(tokenized_processtree_complex, model_glove)
sentence_embeddings_glove_spaghetti = get_sentence_embeddings(tokenized_processtree_spaghetti, model_glove)

NameError: name 'model_glove' is not defined

In [ ]:
sentence_embeddings_glove_naive[0]

array([-0.13051475,  0.20653911,  0.35727904, -0.18217544,  0.26469127,
        0.31946985,  0.51413277,  0.2705608 , -0.4467848 , -0.04649709,
       -0.24146663, -0.08463067, -0.31983573,  0.13432501,  0.42429251,
       -0.29709743,  0.18107216, -0.19235547,  0.41653979, -0.04810624,
       -0.08369027, -0.40233913,  0.1678157 ,  0.40154181,  0.38492003,
       -0.40106161,  0.34772023,  0.12918458,  0.09516265,  0.28268461,
        0.09148969, -0.342434  ,  0.40956091, -0.03983942, -0.16569296,
       -0.04809649,  0.39519941,  0.0956775 ,  0.50312312, -0.1561578 ,
        0.17938171, -0.22845523, -0.01107777,  0.2630351 , -0.42440091,
       -0.11347636,  0.02850744, -0.11472015, -0.20897358,  0.28548765,
       -0.11798517, -0.07325994,  0.35444089,  0.21851703,  0.22846467,
       -0.47502361, -0.31676243,  0.14297502, -0.28459959,  0.20620335,
        0.35528417,  0.12145072,  0.21184301,  0.13505581])

## fasttext

In [ ]:
def sentence_embedding(sentence_tokens, model):
    word_vectors = []
    for token in sentence_tokens:
        if token in model.wv:
            # Keep the original 64-dimensional vector for each word
            word_vector = model.wv[token]
            word_vectors.append(word_vector)
    # Calculate the mean of word vectors along the first axis (axis=0)
    sentence_embedding = np.mean(word_vectors, axis=0)
    return sentence_embedding


In [ ]:
# Create lists to store sentence embeddings for each group
sentence_embeddings_fasttext_naive = []
sentence_embeddings_fasttext_simple = []
sentence_embeddings_fasttext_concise = []
sentence_embeddings_fasttext_straightforward = []
sentence_embeddings_fasttext_complex = []
sentence_embeddings_fasttext_spaghetti = []

# Apply the sentence embeddings to each group
sentence_embeddings_fasttext_naive = get_sentence_embeddings(tokenized_processtree_naive, model_fasttext)
sentence_embeddings_fasttext_simple = get_sentence_embeddings(tokenized_processtree_simple, model_fasttext)
sentence_embeddings_fasttext_concise = get_sentence_embeddings(tokenized_processtree_concise, model_fasttext)
sentence_embeddings_fasttext_straightforward = get_sentence_embeddings(tokenized_processtree_straightforward, model_fasttext)
sentence_embeddings_fasttext_complex = get_sentence_embeddings(tokenized_processtree_complex, model_fasttext)
sentence_embeddings_fasttext_spaghetti = get_sentence_embeddings(tokenized_processtree_spaghetti, model_fasttext)

In [ ]:
sentence_embeddings_fasttext_naive[0]

array([-7.2517335e-01,  4.3731678e-01, -9.3166472e-04,  5.7830024e-01,
        4.7686180e-01,  7.1326661e-01,  2.1321277e-01, -6.1999899e-01,
       -5.1609892e-01, -5.2025975e-03, -4.0212327e-01,  2.8846219e-01,
        6.5103048e-01, -3.4363598e-01,  2.6114997e-01,  5.4892796e-01,
        4.5278186e-01, -3.3694336e-01, -4.1962701e-01, -4.0016338e-01,
       -7.7331245e-01, -2.8436124e-01, -3.8061577e-01,  4.2957225e-01,
       -1.3981728e-01, -8.2011962e-01,  1.0196060e-01, -3.9682397e-01,
       -3.8860503e-01, -4.4027883e-01, -3.5557377e-01, -2.9655674e-01,
        3.4661549e-01,  9.6519679e-01, -8.2099937e-02,  1.3025302e-01,
       -1.4867887e-01, -2.5095502e-01, -4.1880631e-01, -5.6375641e-01,
       -2.5409001e-01,  3.3229709e-01,  2.8767329e-01,  2.7831063e-02,
        2.4312906e-02,  3.5535154e-01,  1.7530729e-01, -2.4784885e-01,
        3.1928033e-01, -2.4948278e-01,  1.6246654e-02,  1.6300054e-01,
        5.4173642e-01, -9.2238343e-01, -3.3119649e-01,  4.2798460e-01,
      

## ELMo

In [ ]:
pip install allennlp

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 730.2/730.2 kB 5.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 776.3/776.3 MB 564.5 kB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.1/19.1 MB 21.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 248.2/248.2 kB 10.9 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 56.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.7/101.7 kB 7.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.4/4.4 MB 46.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 299.2/299.2 kB 22.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 72.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116

In [ ]:
from allennlp.modules.elmo import Elmo, batch_to_ids

options_file = "https://allennlp.s3.amazonaws.com/models/elmo/2x4096_512_2048cnn_2xhighway/elmo_2x4096_512_2048cnn_2xhighway_options.json"
weight_file = "https://allennlp.s3.amazonaws.com/models/elmo/2x4096_512_2048cnn_2xhighway/elmo_2x4096_512_2048cnn_2xhighway_weights.hdf5"

elmo = Elmo(options_file, weight_file, 1, dropout=0)

In [ ]:
character_ids_naive = batch_to_ids(processtree_naive)
character_ids_simple = batch_to_ids(processtree_simple)
character_ids_concise = batch_to_ids(processtree_concise)
character_ids_straightforward= batch_to_ids(processtree_straightforward)
character_ids_complex = batch_to_ids(processtree_complex)
character_ids_spaghetti = batch_to_ids(processtree_spaghetti)

In [ ]:
character_ids_naive.size()

torch.Size([100, 49, 50])

In [ ]:
import torch
with torch.no_grad():
    elmo_embeddings_naive = elmo(character_ids_naive)
    elmo_embeddings_simple = elmo(character_ids_simple)
    elmo_embeddings_concise = elmo(character_ids_concise)
    elmo_embeddings_straightforward = elmo(character_ids_straightforward)
    elmo_embeddings_complex = elmo(character_ids_complex)
    elmo_embeddings_spaghetti = elmo(character_ids_spaghetti)

In [ ]:
# Elmo 임베딩을 평균하여 1차원으로 축소
sentence_embeddings_elmo_naive = np.mean(elmo_embeddings_naive['elmo_representations'][0].detach().numpy(), axis=1)
sentence_embeddings_elmo_simple = np.mean(elmo_embeddings_simple['elmo_representations'][0].detach().numpy(), axis=1)
sentence_embeddings_elmo_concise = np.mean(elmo_embeddings_concise['elmo_representations'][0].detach().numpy(), axis=1)
sentence_embeddings_elmo_straightforward = np.mean(elmo_embeddings_straightforward['elmo_representations'][0].detach().numpy(), axis=1)
sentence_embeddings_elmo_complex = np.mean(elmo_embeddings_complex['elmo_representations'][0].detach().numpy(), axis=1)
sentence_embeddings_elmo_spaghetti = np.mean(elmo_embeddings_spaghetti['elmo_representations'][0].detach().numpy(), axis=1)

# Feature Extraction with Pre-trained model

In [14]:
import torch

# If there's a GPU available...
if torch.cuda.is_available():

    # Tell PyTorch to use the GPU.
    device = torch.device("cuda")

    print('There are %d GPU(s) available.' % torch.cuda.device_count())

    print('We will use the GPU:', torch.cuda.get_device_name(0))

# If not...
else:
    print('No GPU available, using the CPU instead.')
    device = torch.device("cpu")

There are 1 GPU(s) available.
We will use the GPU: Tesla T4


In [39]:
from transformers import BertTokenizer, BertModel, GPT2Tokenizer, GPT2Model, T5Tokenizer, T5Model, XLNetTokenizer, XLNetModel
from sentence_transformers import SentenceTransformer
import torch

# BERT 모델 로드
bert_model_name = 'bert-base-cased' ## uncased가 더 좋은 결과
bert_tokenizer = BertTokenizer.from_pretrained(bert_model_name)
bert_model = BertModel.from_pretrained(bert_model_name).to(device)

# GPT 모델 로드
gpt_model_name = 'gpt2'
gpt_tokenizer = GPT2Tokenizer.from_pretrained(gpt_model_name)
gpt_model = GPT2Model.from_pretrained(gpt_model_name).to(device)

# SBERT 모델 로드
sbert_model_name = 'distilbert-base-nli-mean-tokens'
sbert_model = SentenceTransformer(sbert_model_name).to(device)

# T5 모델 로드
t5_model_name = 't5-base'
t5_tokenizer = T5Tokenizer.from_pretrained(t5_model_name)
t5_model = T5Model.from_pretrained(t5_model_name).to(device)

# XLNet 모델 로드
xlnet_model_name = 'xlnet-base-cased'
xlnet_tokenizer = XLNetTokenizer.from_pretrained(xlnet_model_name)
xlnet_model = XLNetModel.from_pretrained(xlnet_model_name).to(device)

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/436k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/436M [00:00<?, ?B/s]

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


## BERT

In [40]:
def embed_processes_with_bert(tokenized_processes):

    # 임베딩을 저장할 리스트 초기화
    bert_embeddings = []

    # tokenized_processes에 대한 반복문
    for tree_tokens in tokenized_processes:
        # 프로세스 트리를 텍스트로 펼치고 토큰화
        process_tree_text = " ".join(tree_tokens)
        tokens = bert_tokenizer(process_tree_text, return_tensors='pt').to(device)

        # BERT 모델에 입력
        with torch.no_grad():
            output = bert_model(**tokens)

        # [CLS] 토큰의 임베딩 사용
        cls_embedding = output.last_hidden_state[:, 0, :].cpu().squeeze().numpy()

        bert_embeddings.append(cls_embedding)

    # 모든 프로세스 트리에 대한 임베딩이 bert_embeddings에 저장됨
    return bert_embeddings

In [41]:
groups = [tokenized_processtree_naive, tokenized_processtree_simple, tokenized_processtree_concise, tokenized_processtree_straightforward, tokenized_processtree_complex, tokenized_processtree_spaghetti]

bert_embeddings_naive = []
bert_embeddings_simple = []
bert_embeddings_concise = []
bert_embeddings_straightforward = []
bert_embeddings_complex = []
bert_embeddings_spaghetti = []

for idx, group in enumerate(groups):
    bert_embeddings = embed_processes_with_bert(group)

    # 그룹별로 결과를 저장
    if idx == 0:
        bert_embeddings_naive = bert_embeddings
    elif idx == 1:
        bert_embeddings_simple = bert_embeddings
    elif idx == 2:
        bert_embeddings_concise = bert_embeddings
    elif idx == 3:
        bert_embeddings_straightforward = bert_embeddings
    elif idx == 4:
        bert_embeddings_complex = bert_embeddings
    elif idx == 5:
        bert_embeddings_spaghetti = bert_embeddings


## GPT

In [ ]:
def embed_processes_with_gpt(tokenized_processes):

    # 임베딩을 저장할 리스트 초기화
    gpt_embeddings = []

    # tokenized_processes에 대한 반복문
    for tree_tokens in tokenized_processes:
        # 프로세스 트리를 텍스트로 펼치고 토큰화
        process_tree_text = " ".join(tree_tokens)
        tokens = gpt_tokenizer(process_tree_text, return_tensors='pt').to(device)  # 텐서로 변환

        # GPT 모델에 입력
        with torch.no_grad():
            output = gpt_model(**tokens)

        # 마지막 토큰의 임베딩 사용
        last_token_embedding = output.last_hidden_state[:, -1, :].cpu().squeeze().numpy()

        gpt_embeddings.append(last_token_embedding)

    # 모든 프로세스 트리에 대한 임베딩이 gpt_embeddings에 저장됨
    return gpt_embeddings


In [ ]:
groups = [tokenized_processtree_naive, tokenized_processtree_simple, tokenized_processtree_concise, tokenized_processtree_straightforward, tokenized_processtree_complex, tokenized_processtree_spaghetti]

gpt_embeddings_naive = []
gpt_embeddings_simple = []
gpt_embeddings_concise = []
gpt_embeddings_straightforward = []
gpt_embeddings_complex = []
gpt_embeddings_spaghetti = []

for idx, group in enumerate(groups):
    gpt_embeddings = embed_processes_with_gpt(group)

    # 그룹별로 결과를 저장
    if idx == 0:
        gpt_embeddings_naive = gpt_embeddings
    elif idx == 1:
        gpt_embeddings_simple = gpt_embeddings
    elif idx == 2:
        gpt_embeddings_concise = gpt_embeddings
    elif idx == 3:
        gpt_embeddings_straightforward = gpt_embeddings
    elif idx == 4:
        gpt_embeddings_complex = gpt_embeddings
    elif idx == 5:
        gpt_embeddings_spaghetti = gpt_embeddings


##SBERT

In [ ]:
def embed_processes_with_sbert(tokenized_processes):

    # 임베딩을 저장할 리스트 초기화
    sbert_embeddings = []

    # tokenized_processes에 대한 반복문
    for tree_tokens in tokenized_processes:
        # 프로세스 트리를 텍스트로 펼치고 토큰화
        process_tree_text = " ".join(tree_tokens)

        # SBERT 모델을 사용하여 문장 임베딩 얻기
        sbert_embedding = sbert_model.encode([process_tree_text])

        # 평균 풀링
        average_pooled_embedding = np.mean(sbert_embedding, axis=0)
        sbert_embeddings.append(average_pooled_embedding)

    # 모든 프로세스 트리에 대한 임베딩이 sbert_embeddings에 저장됨
    return sbert_embeddings

In [ ]:
groups = [tokenized_processtree_naive, tokenized_processtree_simple, tokenized_processtree_concise, tokenized_processtree_straightforward, tokenized_processtree_complex, tokenized_processtree_spaghetti]

sbert_embeddings_naive = []
sbert_embeddings_simple = []
sbert_embeddings_concise = []
sbert_embeddings_straightforward = []
sbert_embeddings_complex = []
sbert_embeddings_spaghetti = []

for idx, group in enumerate(groups):
    sbert_embeddings = embed_processes_with_sbert(group)

    # 그룹별로 결과를 저장
    if idx == 0:
        sbert_embeddings_naive = sbert_embeddings
    elif idx == 1:
        sbert_embeddings_simple = sbert_embeddings
    elif idx == 2:
        sbert_embeddings_concise = sbert_embeddings
    elif idx == 3:
        sbert_embeddings_straightforward = sbert_embeddings
    elif idx == 4:
        sbert_embeddings_complex = sbert_embeddings
    elif idx == 5:
        sbert_embeddings_spaghetti = sbert_embeddings


## T5

In [ ]:
def embed_processes_with_t5(tokenized_processes):

    # 임베딩을 저장할 리스트 초기화
    t5_embeddings = []

    # tokenized_processes에 대한 반복문
    for tree_tokens in tokenized_processes:
        # 프로세스 트리를 텍스트로 펼치고 토큰화
        process_tree_text = " ".join(tree_tokens)

        # T5 모델에 입력
        inputs = t5_tokenizer(process_tree_text, return_tensors='pt', max_length=512, truncation=True).to(device)
        with torch.no_grad():
            output = t5_model(**inputs, decoder_input_ids=inputs["input_ids"])

        # 평균풀링 사용
        average_pooled_embedding = output.last_hidden_state.mean(dim=1).cpu().squeeze().numpy()

        t5_embeddings.append(average_pooled_embedding)

    # 모든 프로세스 트리에 대한 임베딩이 t5_embeddings에 저장됨
    return t5_embeddings

In [ ]:
groups = [tokenized_processtree_naive, tokenized_processtree_simple, tokenized_processtree_concise, tokenized_processtree_straightforward, tokenized_processtree_complex, tokenized_processtree_spaghetti]

t5_embeddings_naive = []
t5_embeddings_simple = []
t5_embeddings_concise = []
t5_embeddings_straightforward = []
t5_embeddings_complex = []
t5_embeddings_spaghetti = []

for idx, group in enumerate(groups):
    t5_embeddings = embed_processes_with_t5(group)

    # 그룹별로 결과를 저장
    if idx == 0:
        t5_embeddings_naive = t5_embeddings
    elif idx == 1:
        t5_embeddings_simple = t5_embeddings
    elif idx == 2:
        t5_embeddings_concise = t5_embeddings
    elif idx == 3:
        t5_embeddings_straightforward = t5_embeddings
    elif idx == 4:
        t5_embeddings_complex = t5_embeddings
    elif idx == 5:
        t5_embeddings_spaghetti = t5_embeddings


## XLNet

In [ ]:
def embed_processes_with_xlnet(tokenized_processes):

    # 임베딩을 저장할 리스트 초기화
    xlnet_embeddings = []

    # tokenized_processes에 대한 반복문
    for tree_tokens in tokenized_processes:
        # 프로세스 트리를 텍스트로 펼치고 토큰화
        process_tree_text = " ".join(tree_tokens)
        tokens = xlnet_tokenizer(process_tree_text, return_tensors='pt').to(device)  # 텐서로 변환

        # XLNet 모델에 입력
        with torch.no_grad():
            output = xlnet_model(**tokens)

        # 평균풀링 사용
        average_pooled_embedding = output.last_hidden_state.mean(dim=1).cpu().squeeze().numpy()

        xlnet_embeddings.append(average_pooled_embedding)

    # 모든 프로세스 트리에 대한 임베딩이 xlnet_embeddings에 저장됨
    return xlnet_embeddings


In [ ]:
groups = [tokenized_processtree_naive, tokenized_processtree_simple, tokenized_processtree_concise, tokenized_processtree_straightforward, tokenized_processtree_complex, tokenized_processtree_spaghetti]

xlnet_embeddings_naive = []
xlnet_embeddings_simple = []
xlnet_embeddings_concise = []
xlnet_embeddings_straightforward = []
xlnet_embeddings_complex = []
xlnet_embeddings_spaghetti = []

for idx, group in enumerate(groups):
    xlnet_embeddings = embed_processes_with_xlnet(group)

    # 그룹별로 결과를 저장
    if idx == 0:
        xlnet_embeddings_naive = xlnet_embeddings
    elif idx == 1:
        xlnet_embeddings_simple = xlnet_embeddings
    elif idx == 2:
        xlnet_embeddings_concise = xlnet_embeddings
    elif idx == 3:
        xlnet_embeddings_straightforward = xlnet_embeddings
    elif idx == 4:
        xlnet_embeddings_complex = xlnet_embeddings
    elif idx == 5:
        xlnet_embeddings_spaghetti = xlnet_embeddings


# SSL with Pre-trained model

In [42]:
import random
import string

def mask_data(sentence_tokens, mask_ratio=0.15):
    masked_tokens = list(sentence_tokens)

    # Identify the lowercase alphabet tokens in the sentence
    alphabet_tokens = [token for token in sentence_tokens if token.isalpha() and token.islower()]

    # Randomly select lowercase alphabet tokens to mask
    tokens_to_mask = random.sample(alphabet_tokens, int(len(alphabet_tokens) * mask_ratio))

    for token in tokens_to_mask:
        masked_tokens[masked_tokens.index(token)] = "[MASK]"

    return masked_tokens

def replace_data(sentence_tokens, replace_ratio=0.15, vocab_size=10000):
    replaced_tokens = list(sentence_tokens)

    # Identify the lowercase alphabet tokens in the sentence
    alphabet_tokens = [token for token in sentence_tokens if token.isalpha() and token.islower()]

    # Randomly select lowercase alphabet tokens to replace
    tokens_to_replace = random.sample(alphabet_tokens, int(len(alphabet_tokens) * replace_ratio))

    # Generate a vocabulary of random lowercase alphabet tokens
    random_vocab = [random.choice(string.ascii_lowercase) for _ in range(vocab_size)]

    for token in tokens_to_replace:
        # Replace with a new lowercase token from the given vocabulary
        new_token = random.choice(random_vocab)
        replaced_tokens[replaced_tokens.index(token)] = new_token

    return replaced_tokens

In [28]:
# 새로운 리스트 초기화
masked_processtrees = []

# all_tokenized_processtrees에 대한 반복문
for tree_tokens in all_tokenized_processtrees:
    # 각 트리에 대해 mask_data 함수를 호출하여 masked_tokens를 얻음
    masked_tokens = mask_data(tree_tokens)

    # masked_tokens를 새로운 리스트에 추가
    masked_processtrees.append(masked_tokens)

In [29]:
# 새로운 리스트 초기화
replaced_processtrees = []

# all_tokenized_processtrees에 대한 반복문
for tree_tokens in all_tokenized_processtrees:
    # 각 트리에 대해 mask_data 함수를 호출하여 masked_tokens를 얻음
    replaced_tokens = replace_data(tree_tokens)

    # masked_tokens를 새로운 리스트에 추가
    replaced_processtrees.append(replaced_tokens)

In [30]:
augmented_processtrees = masked_processtrees + replaced_processtrees

In [31]:
decoded_sentences = []
for tree_tokens in augmented_processtrees:
    # 공백으로 구분된 단어들을 하나의 문자열로 합침
    decoded_tree = ' '.join(tree_tokens)
    decoded_sentences.append(decoded_tree)

In [43]:
from torch.utils.data import DataLoader, Dataset
import torch

# 데이터셋 클래스 정의
class CustomDataset(Dataset):
    def __init__(self, data, tokenizer, max_length=128):
        self.data = data
        self.tokenizer = tokenizer
        self.max_length = max_length

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        encoded = self.tokenizer(self.data[idx], return_tensors='pt', truncation=True, padding='max_length', max_length=self.max_length)
        return {
            'input_ids': encoded['input_ids'].squeeze(),
            'attention_mask': encoded['attention_mask'].squeeze(),
        }

In [44]:
# BERT 데이터 로딩
bert_dataset = CustomDataset(decoded_sentences, bert_tokenizer)
bert_dataloader = DataLoader(bert_dataset, batch_size=2, shuffle=True)

In [45]:
#Optimizer 설정
optimizer = torch.optim.AdamW(bert_model.parameters(), lr=5e-5)

#스케줄러 설정
from transformers import get_scheduler

num_epochs = 3
num_training_steps = num_epochs * len(bert_dataloader)
lr_scheduler = get_scheduler(
    'linear',
    optimizer=optimizer,
    num_warmup_steps=0,
    num_training_steps=num_training_steps
)

#진행과정을 보기 위해서 tqdm 라이브러리 사용
from tqdm.auto import tqdm

import torch.nn.functional as F

print(num_training_steps)

1800


## BERT

In [46]:
progress_bar = tqdm(range(num_training_steps))

bert_model.train()

for epoch in range(num_epochs):  # 적절한 에폭 수 설정
    for batch in bert_dataloader:
        batch = {k: v.to(device) for k, v in batch.items()}
        outputs = bert_model(**batch)
        # 예측된 로짓
        logits = outputs.last_hidden_state

        # 실제 마스크된 토큰
        masked_tokens = batch['input_ids'] == bert_tokenizer.mask_token_id

        # 손실 계산
        loss = F.cross_entropy(logits[masked_tokens], batch['input_ids'][masked_tokens])

        loss.backward()
        optimizer.step()
        optimizer.zero_grad()
        progress_bar.update(1)

  0%|          | 0/1800 [00:00<?, ?it/s]

In [47]:
groups = [tokenized_processtree_naive, tokenized_processtree_simple, tokenized_processtree_concise, tokenized_processtree_straightforward, tokenized_processtree_complex, tokenized_processtree_spaghetti]

SSL_bert_embeddings_naive = []
SSL_bert_embeddings_simple = []
SSL_bert_embeddings_concise = []
SSL_bert_embeddings_straightforward = []
SSL_bert_embeddings_complex = []
SSL_bert_embeddings_spaghetti = []

for idx, group in enumerate(groups):
    bert_embeddings = embed_processes_with_bert(group)

    # 그룹별로 결과를 저장
    if idx == 0:
        SSL_bert_embeddings_naive = bert_embeddings
    elif idx == 1:
        SSL_bert_embeddings_simple = bert_embeddings
    elif idx == 2:
        SSL_bert_embeddings_concise = bert_embeddings
    elif idx == 3:
        SSL_bert_embeddings_straightforward = bert_embeddings
    elif idx == 4:
        SSL_bert_embeddings_complex = bert_embeddings
    elif idx == 5:
        SSL_bert_embeddings_spaghetti = bert_embeddings

# Levenshtein(edit) distance-based similarity among Linear Process Trees (Baseline)

In [13]:
import Levenshtein

def calculate_levenshtein_distance(tree1, tree2):
    str_tree1 = str(tree1).replace(" ", "").replace("'", "").replace('tau', '0')
    str_tree2 = str(tree2).replace(" ", "").replace("'", "").replace('tau', '0')
    distance = Levenshtein.distance(str_tree1, str_tree2)
    return distance

def calculate_similarity(tree1, tree2):
    max_distance = max(len(str(tree1)), len(str(tree2)))
    distance = calculate_levenshtein_distance(tree1, tree2)
    similarity = 1 - (distance / max_distance)
    return similarity

def calculate_average_similarity(tree_group1, tree_group2):
    total_similarity = 0.0

    for tree1 in tree_group1:
        for tree2 in tree_group2:
            similarity = calculate_similarity(tree1, tree2)
            total_similarity += similarity

    # 프로세스 트리 쌍의 총 수
    total_pairs = len(tree_group1) * len(tree_group2)

    # 전체 유사도의 평균
    average_similarity = total_similarity / total_pairs

    return average_similarity


In [46]:
# 주어진 트리 데이터
groups = [processtree_naive, processtree_simple, processtree_concise, processtree_straightforward, processtree_complex, processtree_spaghetti]

# 각 트리에 대해 반복하면서 괄호와 공백 제거
for i, tree_list in enumerate(groups):
    for j, tree in enumerate(tree_list):
        # 공백 제거
        tree_without_spaces = tree.replace(' ', '')
        # 결과 출력 또는 다른 작업 수행
        groups[i][j] = tree_without_spaces 

In [54]:
groups = [processtree_naive, processtree_simple, processtree_concise, processtree_straightforward, processtree_complex,processtree_spaghetti]

# Initialize a 6x6 matrix for similarities
similarity_matrix = np.zeros((6, 6))

# Calculate and update the matrix with average similarity for each pair of groups
for i, group1 in enumerate(groups):
    for j, group2 in enumerate(groups):
        average_similarity = calculate_average_similarity(group1, group2)

        # Update the matrix with similarity values (both symmetric positions)
        similarity_matrix[i][j] = average_similarity

# Print the similarity matrix
print("Similarity Matrix:")
print(similarity_matrix) ## 원본데이터 그대로

Similarity Matrix:
[[0.78843265 0.75646643 0.70630381 0.63141503 0.63046545 0.61427472]
 [0.75646643 0.74987514 0.7100797  0.61731961 0.62430348 0.61303696]
 [0.70630381 0.7100797  0.71652799 0.59769216 0.60506453 0.61277752]
 [0.63141503 0.61731961 0.59769216 0.76136601 0.7353943  0.68967341]
 [0.63046545 0.62430348 0.60506453 0.7353943  0.73060546 0.69289445]
 [0.61427472 0.61303696 0.61277752 0.68967341 0.69289445 0.69846965]]


In [38]:
groups = [processtree_naive, processtree_simple, processtree_concise, processtree_straightforward, processtree_complex,processtree_spaghetti]

# Initialize a 6x6 matrix for similarities
similarity_matrix = np.zeros((6, 6))

# Calculate and update the matrix with average similarity for each pair of groups
for i, group1 in enumerate(groups):
    for j, group2 in enumerate(groups):
        average_similarity = calculate_average_similarity(group1, group2)

        # Update the matrix with similarity values (both symmetric positions)
        similarity_matrix[i][j] = average_similarity

# Print the similarity matrix
print("Similarity Matrix:")
print(similarity_matrix) ## 공백만 제거

Similarity Matrix:
[[0.585328   0.52238424 0.42393415 0.26761688 0.265778   0.23357172]
 [0.52238424 0.50941232 0.43135318 0.23960909 0.25353669 0.23111158]
 [0.42393415 0.43135318 0.44399746 0.20060909 0.2153156  0.23059511]
 [0.26761688 0.23960909 0.20060909 0.52583117 0.47408177 0.38321651]
 [0.265778   0.25353669 0.2153156  0.47408177 0.46451201 0.38955469]
 [0.23357172 0.23111158 0.23059511 0.38321651 0.38955469 0.40063627]]


# graph edit distance driven similarity

## 정의

In [10]:
class TreeNode:
    def __init__(self, value):
        self.value = value
        self.children = []

    def add_child(self, child):
        self.children.append(child)

    def print_tree(self, depth=0):
        print("  " * depth + self.value)
        for child in self.children:
            child.print_tree(depth + 1)
    def count_nodes(self):
        # 현재 노드를 포함하여 노드 수 계산
        count = 1
        for child in self.children:
            count += child.count_nodes()
        return count

    def count_edges(self):
        # 현재 노드의 자식 수를 엣지로 간주하여 엣지 수 계산
        edge_count = len(self.children)
        for child in self.children:
            edge_count += child.count_edges()
        return edge_count

In [11]:
def tree_edit_distance(A, B):
    # 노드 A를 루트로 하는 트리와 노드 B를 루트로 하는 트리 사이의 최소 편집 거리를 계산
    def min_distance(root1, root2, memo):
        if (root1, root2) in memo:
            return memo[(root1, root2)]
        elif root1 is None and root2 is None:
            return 0
        elif root1 is None:
            return 1 + sum(min_distance(None, child, memo) for child in root2.children)
        elif root2 is None:
            return 1 + sum(min_distance(child, None, memo) for child in root1.children)
        else:
            cost = 0 if root1.value == root2.value else 1
            
            # 두 노드의 자식들을 매칭
            from itertools import permutations
            children1 = root1.children
            children2 = root2.children
            size1, size2 = len(children1), len(children2)
            min_cost = float('inf')

            # 모든 가능한 자식 노드들의 순열에 대해 편집 거리를 계산
            for perm in permutations(children2):
                # 자식들 간 비용 계산
                current_cost = sum(min_distance(child1, child2, memo) for child1, child2 in zip(children1, perm))
                current_cost += abs(size1 - size2)  # 차이나는 자식 수만큼 추가 또는 삭제 비용
                min_cost = min(min_cost, current_cost)
                
            memo[(root1, root2)] = cost + min_cost
            return memo[(root1, root2)]

    # 메모이제이션을 위한 딕셔너리
    memo = {}
    return min_distance(A, B, memo)

In [12]:
def text_to_tree(sentence):
    stack = []
    root = TreeNode(None)
    sentence = sentence.replace(" ", "")
    for i in range(len(sentence)):
        if sentence[i] != '(' and sentence[i] != ')':
            cur = sentence[i]
            child = TreeNode(cur)
            root.add_child(child)
        elif sentence[i] == '(':
            stack.append(child)
            root = child
        else:
            stack.pop()
            if stack != []:
                root = stack[-1]
            

    return root

In [19]:
processtree_naive[0]

'→ ( a → ( → ( d → ( e → ( b f ) ) ) → ( c g ) ) )'

In [23]:
root = text_to_tree(processtree_straightforward[0])

root.print_tree()

→
  →
    →
      →
        d
        f
      →
        c
        →
          →
            n
            →
              s
              q
          →
            j
            t
    →
      →
        e
        →
          →
            i
            h
          →
            →
              m
              g
            →
              p
              k
      →
        b
        r
  →
    a
    →
      o
      l


In [13]:
def max_edit_distance(graph1, graph2):
    # 그래프의 노드 수와 엣지 수 계산
    node_count1 = graph1.count_nodes()
    edge_count1 = graph1.count_edges()
    node_count2 = graph2.count_nodes()
    edge_count2 = graph2.count_edges()

    # 두 그래프의 노드 수와 엣지 수 중에서 더 큰 값을 최대 편집 거리로 지정
    max_node_count = max(node_count1, node_count2)
    max_edge_count = max(edge_count1, edge_count2)

    return max_node_count + max_edge_count

In [20]:
def graph_edit_similarity(sentence1, sentence2):
    graph1 = text_to_tree(sentence1)
    graph2 = text_to_tree(sentence2)
    
    ged = tree_edit_distance(graph1, graph2)
    maxged = max_edit_distance(graph1, graph2)
    print(ged)
    print(maxged)
    sim = 1 - (ged / maxged)
    print(sim)

In [15]:
def ged_average_similarity(tree_group1, tree_group2):
    total_similarity = 0.0

    for tree1 in tree_group1:
        for tree2 in tree_group2:
            similarity = graph_edit_similarity(tree1, tree2)
            total_similarity += similarity

    # 프로세스 트리 쌍의 총 수
    total_pairs = len(tree_group1) * len(tree_group2)

    # 전체 유사도의 평균
    average_similarity = total_similarity / total_pairs

    return average_similarity


In [21]:
graph_edit_similarity(processtree_naive[0], processtree_naive[2])

9
25
0.64


In [22]:
graph_edit_similarity(processtree_naive[0], processtree_straightforward[2])

6
77
0.922077922077922


## 계산

In [23]:
groups = [processtree_naive, processtree_simple, processtree_concise, processtree_straightforward, processtree_complex,processtree_spaghetti]

# Initialize a 6x6 matrix for similarities
similarity_matrix = np.zeros((6, 6))

# Calculate and update the matrix with average similarity for each pair of groups
for i, group1 in enumerate(groups):
    for j, group2 in enumerate(groups):
        average_similarity = ged_average_similarity(group1, group2)

        # Update the matrix with similarity values (both symmetric positions)
        similarity_matrix[i][j] = average_similarity

# Print the similarity matrix
print("Similarity Matrix:")
print(similarity_matrix) ##공백 제거

Similarity Matrix:
[[0.702496   0.67467435 0.61145146 0.85583377 0.83874985 0.81629182]
 [0.67467435 0.67650865 0.63023166 0.84727792 0.840912   0.82588855]
 [0.61145146 0.63023166 0.63729924 0.82036104 0.82053182 0.82477385]
 [0.85583377 0.84727792 0.82036104 0.78927532 0.77335379 0.73737769]
 [0.83874985 0.840912   0.82053182 0.77335379 0.77196617 0.74318053]
 [0.81629182 0.82588855 0.82477385 0.73737769 0.74318053 0.74777716]]


# 그룹별 유사도 계산

## cosine 유사도 함수 정의

In [37]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

def cosine_avg(embeddings_groups):
    num_groups = len(embeddings_groups)
    similarity_matrix = np.zeros((num_groups, num_groups))

    for i in range(num_groups):
        for j in range(num_groups):
            embeddings1 = embeddings_groups[i]
            embeddings2 = embeddings_groups[j]

            similarity_matrix[i, j] = np.mean(cosine_similarity(embeddings1, embeddings2))

    # Print the similarity matrix
    print("Similarity Matrix:")
    print(similarity_matrix)

In [ ]:
embeddings_groups_bow = [bows_naive, bows_simple, bows_concise, bows_straightforward, bows_complex, bows_spaghetti]
cosine_avg(embeddings_groups_bow)

Similarity Matrix:
[[1.         0.95711048 0.84082237 0.97991578 0.94838576 0.84755838]
 [0.95711048 0.97007336 0.89499346 0.93513912 0.95890636 0.89325184]
 [0.84082237 0.89499346 0.94754781 0.81422148 0.87836842 0.93970216]
 [0.97991578 0.93513912 0.81422148 1.         0.96652602 0.86346964]
 [0.94838576 0.95890636 0.87836842 0.96652602 0.99009108 0.92184794]
 [0.84755838 0.89325184 0.93970216 0.86346964 0.92184794 0.98171865]]


In [ ]:
embeddings_groups_tfidf = [sentence_embeddings_tfidf_naive, sentence_embeddings_tfidf_simple, sentence_embeddings_tfidf_concise, sentence_embeddings_tfidf_straightforward, sentence_embeddings_tfidf_complex, sentence_embeddings_tfidf_spaghetti]
cosine_avg(embeddings_groups_tfidf)

Similarity Matrix:
[[1.         0.93217151 0.73278585 0.96888458 0.91394503 0.73900172]
 [0.93217151 0.9539118  0.79174779 0.90155068 0.93571473 0.78793142]
 [0.73278585 0.79174779 0.88829434 0.70234891 0.77161798 0.89008379]
 [0.96888458 0.90155068 0.70234891 1.         0.94222203 0.76524119]
 [0.91394503 0.93571473 0.77161798 0.94222203 0.9784762  0.82679795]
 [0.73900172 0.78793142 0.89008379 0.76524119 0.82679795 0.95303866]]


In [ ]:
embeddings_groups_w2v = [sentence_embeddings_w2v_naive, sentence_embeddings_w2v_simple, sentence_embeddings_w2v_concise, sentence_embeddings_w2v_straightforward, sentence_embeddings_w2v_complex, sentence_embeddings_w2v_spaghetti]
cosine_avg(embeddings_groups_w2v)

Similarity Matrix:
[[1.         0.98134279 0.85440928 0.99542618 0.97284853 0.84466136]
 [0.98134279 0.98703641 0.91117263 0.98520666 0.9862535  0.90532005]
 [0.8544094  0.91117263 0.97674787 0.87320364 0.92698938 0.97953486]
 [0.99542618 0.98520666 0.87320364 1.         0.98593438 0.87177032]
 [0.97284853 0.98625344 0.92698944 0.9859345  0.996301   0.93132752]
 [0.84466124 0.90531993 0.97953498 0.87177032 0.93132752 0.99261689]]


In [ ]:
embeddings_groups_glove = [sentence_embeddings_glove_naive, sentence_embeddings_glove_simple, sentence_embeddings_glove_concise, sentence_embeddings_glove_straightforward, sentence_embeddings_glove_complex, sentence_embeddings_glove_spaghetti]
cosine_avg(embeddings_groups_glove)

Similarity Matrix:
[[1.         0.99745099 0.9807007  0.99586322 0.99457582 0.97976461]
 [0.99745099 0.99833072 0.98890595 0.99238626 0.99478856 0.98719099]
 [0.9807007  0.98890595 0.99735569 0.9733746  0.9836915  0.99374906]
 [0.99586322 0.99238626 0.9733746  1.         0.99771792 0.98093089]
 [0.99457582 0.99478856 0.9836915  0.99771792 0.99941597 0.99043406]
 [0.97976461 0.98719099 0.99374906 0.98093089 0.99043406 0.99891355]]


In [ ]:
embeddings_groups_fasttext = [sentence_embeddings_fasttext_naive, sentence_embeddings_fasttext_simple, sentence_embeddings_fasttext_concise, sentence_embeddings_fasttext_straightforward, sentence_embeddings_fasttext_complex, sentence_embeddings_fasttext_spaghetti]
cosine_avg(embeddings_groups_fasttext)

Similarity Matrix:
[[1.         0.98333758 0.86897618 0.99622637 0.97627813 0.86179298]
 [0.9833377  0.98850363 0.92131847 0.98764592 0.9885335  0.91679949]
 [0.86897618 0.92131835 0.97968066 0.8905471  0.93912441 0.98322517]
 [0.99622637 0.98764598 0.89054698 1.         0.98796135 0.88938504]
 [0.97627813 0.98853338 0.93912452 0.98796135 0.99686199 0.94181144]
 [0.86179298 0.91679949 0.98322517 0.88938498 0.94181132 0.9939127 ]]


In [ ]:
embeddings_groups_elmo = [sentence_embeddings_elmo_naive, sentence_embeddings_elmo_simple, sentence_embeddings_elmo_concise, sentence_embeddings_elmo_straightforward, sentence_embeddings_elmo_complex, sentence_embeddings_elmo_spaghetti]
cosine_avg(embeddings_groups_elmo)

Similarity Matrix:
[[0.99589705 0.98856896 0.96873474 0.98408967 0.98322111 0.96917373]
 [0.98856896 0.98998934 0.97357315 0.97257781 0.98154014 0.97263789]
 [0.96873474 0.97357315 0.97179335 0.95182228 0.9641338  0.96922463]
 [0.98408967 0.97257781 0.95182228 0.99716961 0.98946369 0.97192073]
 [0.98322111 0.98154014 0.96413368 0.98946369 0.99462956 0.98353088]
 [0.96917373 0.97263789 0.96922463 0.97192073 0.98353094 0.99004924]]


In [ ]:
#uncased
embeddings_groups_bert = [bert_embeddings_naive, bert_embeddings_simple, bert_embeddings_concise, bert_embeddings_straightforward, bert_embeddings_complex, bert_embeddings_spaghetti]
cosine_avg(embeddings_groups_bert)

Similarity Matrix:
[[0.98441672 0.95964354 0.91074258 0.91833556 0.92161369 0.89787966]
 [0.95964354 0.95735657 0.92373967 0.88873655 0.91884339 0.9063881 ]
 [0.91074258 0.92373967 0.94348967 0.83422804 0.88044649 0.91547978]
 [0.91833556 0.88873655 0.83422804 0.98699629 0.95215213 0.9062137 ]
 [0.92161375 0.91884339 0.88044649 0.95215213 0.96733928 0.93718582]
 [0.8978796  0.9063881  0.91547978 0.90621376 0.93718576 0.96597433]]


In [ ]:
#cased
embeddings_groups_bert = [bert_embeddings_naive, bert_embeddings_simple, bert_embeddings_concise, bert_embeddings_straightforward, bert_embeddings_complex, bert_embeddings_spaghetti]
cosine_avg(embeddings_groups_bert)

Similarity Matrix:
[[0.9971658  0.99324638 0.9847489  0.97752225 0.97952324 0.97744179]
 [0.99324638 0.9933424  0.9867503  0.97112519 0.97687024 0.97593176]
 [0.98474884 0.9867503  0.98887068 0.95702195 0.96433836 0.97020841]
 [0.97752225 0.97112519 0.95702195 0.99589431 0.9907217  0.98547566]
 [0.97952336 0.97687012 0.96433848 0.9907217  0.99227607 0.98755652]
 [0.97744179 0.97593164 0.97020841 0.98547578 0.98755652 0.99143136]]


In [ ]:
embeddings_groups_gpt = [gpt_embeddings_naive, gpt_embeddings_simple, gpt_embeddings_concise, gpt_embeddings_straightforward, gpt_embeddings_complex, gpt_embeddings_spaghetti]
cosine_avg(embeddings_groups_gpt)

Similarity Matrix:
[[0.999291   0.9989205  0.99834353 0.99726522 0.99837166 0.9983663 ]
 [0.9989205  0.99882352 0.99836874 0.99718952 0.99827188 0.99823439]
 [0.99834347 0.99836874 0.99850732 0.99746937 0.99786913 0.99798113]
 [0.99726522 0.99718952 0.99746937 0.99947166 0.99795955 0.9972114 ]
 [0.99837166 0.99827188 0.99786913 0.99795955 0.99865437 0.99829113]
 [0.9983663  0.99823439 0.99798113 0.9972114  0.99829113 0.99839139]]


In [ ]:
embeddings_groups_sbert = [sbert_embeddings_naive, sbert_embeddings_simple, sbert_embeddings_concise, sbert_embeddings_straightforward, sbert_embeddings_complex, sbert_embeddings_spaghetti]
cosine_avg(embeddings_groups_sbert)

Similarity Matrix:
[[0.98951513 0.9628697  0.91250193 0.90923613 0.90115917 0.87727976]
 [0.9628697  0.96512508 0.93304932 0.87293875 0.88414061 0.8755632 ]
 [0.91250193 0.93304932 0.94392794 0.80321991 0.82933456 0.85813242]
 [0.90923613 0.87293875 0.80321991 0.99033982 0.97566122 0.93679404]
 [0.90115917 0.88414061 0.82933456 0.97566122 0.98130548 0.95728409]
 [0.87727988 0.8755632  0.85813242 0.93679404 0.95728397 0.97354043]]


In [ ]:
embeddings_groups_t5 = [t5_embeddings_naive, t5_embeddings_simple, t5_embeddings_concise, t5_embeddings_straightforward, t5_embeddings_complex, t5_embeddings_spaghetti]
cosine_avg(embeddings_groups_t5)

Similarity Matrix:
[[0.99855554 0.9930951  0.98440295 0.99485779 0.98368984 0.98453575]
 [0.9930951  0.99558103 0.99017882 0.99185604 0.99098176 0.99112821]
 [0.98440295 0.99017882 0.99085009 0.98278165 0.9855637  0.98970145]
 [0.99485779 0.99185604 0.98278153 0.99896699 0.99112225 0.98786253]
 [0.98368984 0.99098176 0.9855637  0.99112225 0.997159   0.99244159]
 [0.98453575 0.99112821 0.98970145 0.98786253 0.99244159 0.99387324]]


In [ ]:
embeddings_groups_xlnet = [xlnet_embeddings_naive, xlnet_embeddings_simple, xlnet_embeddings_concise, xlnet_embeddings_straightforward, xlnet_embeddings_complex, xlnet_embeddings_spaghetti]
cosine_avg(embeddings_groups_xlnet)

Similarity Matrix:
[[0.99897003 0.99790066 0.99569494 0.99809659 0.99796915 0.99739939]
 [0.99790066 0.99776554 0.99606931 0.9967497  0.99706858 0.99672794]
 [0.99569494 0.99606931 0.99620163 0.99385917 0.99434686 0.99492425]
 [0.99809659 0.9967497  0.99385917 0.99985647 0.99958938 0.9988668 ]
 [0.99796921 0.99706858 0.99434686 0.99958926 0.99973869 0.99914062]
 [0.99739939 0.99672794 0.99492425 0.99886692 0.99914062 0.99956018]]


In [38]:
#uncased

embeddings_groups_bert_SSL = [SSL_bert_embeddings_naive, SSL_bert_embeddings_simple, SSL_bert_embeddings_concise, SSL_bert_embeddings_straightforward, SSL_bert_embeddings_complex, SSL_bert_embeddings_spaghetti]
cosine_avg(embeddings_groups_bert_SSL)

Similarity Matrix:
[[0.87452596 0.87258732 0.86393154 0.86671317 0.86629558 0.86936599]
 [0.87258732 0.87524396 0.8672626  0.86577493 0.86711162 0.87205642]
 [0.86393142 0.86726272 0.8661586  0.85654461 0.85932648 0.86819112]
 [0.86671317 0.86577493 0.85654455 0.87896562 0.87710565 0.88035208]
 [0.86629558 0.86711174 0.85932648 0.87710565 0.87895501 0.88208318]
 [0.86936599 0.87205642 0.868191   0.88035208 0.88208318 0.89270979]]


In [48]:
#cased

embeddings_groups_bert_SSL = [SSL_bert_embeddings_naive, SSL_bert_embeddings_simple, SSL_bert_embeddings_concise, SSL_bert_embeddings_straightforward, SSL_bert_embeddings_complex, SSL_bert_embeddings_spaghetti]
cosine_avg(embeddings_groups_bert_SSL)

Similarity Matrix:
[[0.84419864 0.83771873 0.82596201 0.83397305 0.84084046 0.83733439]
 [0.83771873 0.83977616 0.83074766 0.82336366 0.83313298 0.83206278]
 [0.82596201 0.83074778 0.83067667 0.80625224 0.81820852 0.82150155]
 [0.83397305 0.82336366 0.80625224 0.85040325 0.85136735 0.84362048]
 [0.84084046 0.8331331  0.81820852 0.85136735 0.85762453 0.85051769]
 [0.83733439 0.83206278 0.82150155 0.84362048 0.85051769 0.85009062]]


In [ ]:
embeddings_groups_xlnet_SSL = [SSL_xlnet_embeddings_naive, SSL_xlnet_embeddings_simple, SSL_xlnet_embeddings_concise, SSL_xlnet_embeddings_straightforward, SSL_xlnet_embeddings_complex, SSL_xlnet_embeddings_spaghetti]
cosine_avg(embeddings_groups_xlnet_SSL)

Similarity Matrix:
[[0.99522072 0.99394161 0.9909423  0.99513078 0.99500257 0.99438137]
 [0.99394161 0.99366063 0.99105048 0.99355501 0.99398464 0.99368328]
 [0.9909423  0.99105048 0.99091452 0.98902959 0.98968035 0.99085486]
 [0.99513078 0.99355501 0.98902959 0.99919415 0.9988662  0.99756759]
 [0.99500257 0.99398464 0.98968035 0.9988662  0.9990198  0.99790019]
 [0.99438137 0.99368322 0.99085486 0.99756759 0.99790019 0.9982003 ]]


# 노트

In [ ]:
import torch

# If there's a GPU available...
if torch.cuda.is_available():

    # Tell PyTorch to use the GPU.
    device = torch.device("cuda")

    print('There are %d GPU(s) available.' % torch.cuda.device_count())

    print('We will use the GPU:', torch.cuda.get_device_name(0))

# If not...
else:
    print('No GPU available, using the CPU instead.')
    device = torch.device("cpu")

There are 1 GPU(s) available.
We will use the GPU: Tesla T4
